@echo off
echo before %time%
py -3 rope_new.py <%1\test0.txt >out_py_new.txt
py -3 rope_new.py <%1\test1.txt >out_py_new.txt
py -3 rope_new.py <%1\test2.txt >out_py_new.txt
py -3 rope_new.py <%1\test3.txt >out_py_new.txt
py -3 rope_new.py <%1\test4.txt >out_py_new.txt
py -3 rope_new.py <%1\test5.txt >out_py_new.txt
py -3 rope_new.py <%1\test6.txt >out_py_new.txt
py -3 rope_new.py <%1\test7.txt >out_py_new.txt
py -3 rope_new.py <%1\test8.txt >out_py_new.txt
py -3 rope_new.py <%1\test9.txt >out_py_new.txt
py -3 rope_new.py <%1\test10.txt >out_py_new.txt
py -3 rope_new.py <%1\test11.txt >out_py_new.txt
py -3 rope_new.py <%1\test12.txt >out_py_new.txt
py -3 rope_new.py <%1\test13.txt >out_py_new.txt
py -3 rope_new.py <%1\test14.txt >out_py_new.txt
py -3 rope_new.py <%1\test15.txt >out_py_new.txt
py -3 rope_new.py <%1\test16.txt >out_py_new.txt
py -3 rope_new.py <%1\test17.txt >out_py_new.txt
py -3 rope_new.py <%1\test18.txt >out_py_new.txt
py -3 rope_new.py <%1\test19.txt >out_py_new.txt
py -3 rope_new.py <%1\test20.txt >out_py_new.txt
py -3 rope_new.py <%1\test21.txt >out_py_new.txt
py -3 rope_new.py <%1\test22.txt >out_py_new.txt
py -3 rope_new.py <%1\test23.txt >out_py_new.txt
py -3 rope_new.py <%1\test24.txt >out_py_new.txt
py -3 rope_new.py <%1\test25.txt >out_py_new.txt
py -3 rope_new.py <%1\test26.txt >out_py_new.txt
py -3 rope_new.py <%1\test27.txt >out_py_new.txt
py -3 rope_new.py <%1\test28.txt >out_py_new.txt
py -3 rope_new.py <%1\test29.txt >out_py_new.txt
py -3 rope_new.py <%1\test30.txt >out_py_new.txt
py -3 rope_new.py <%1\test31.txt >out_py_new.txt
py -3 rope_new.py <%1\test32.txt >out_py_new.txt
py -3 rope_new.py <%1\test33.txt >out_py_new.txt
py -3 rope_new.py <%1\test34.txt >out_py_new.txt
py -3 rope_new.py <%1\test35.txt >out_py_new.txt
py -3 rope_new.py <%1\test36.txt >out_py_new.txt
py -3 rope_new.py <%1\test37.txt >out_py_new.txt
py -3 rope_new.py <%1\test38.txt >out_py_new.txt
py -3 rope_new.py <%1\test39.txt >out_py_new.txt
py -3 rope_new.py <%1\test40.txt >out_py_new.txt
py -3 rope_new.py <%1\test41.txt >out_py_new.txt
py -3 rope_new.py <%1\test42.txt >out_py_new.txt
py -3 rope_new.py <%1\test43.txt >out_py_new.txt
py -3 rope_new.py <%1\test44.txt >out_py_new.txt
py -3 rope_new.py <%1\test45.txt >out_py_new.txt
py -3 rope_new.py <%1\test46.txt >out_py_new.txt
py -3 rope_new.py <%1\test47.txt >out_py_new.txt
py -3 rope_new.py <%1\test48.txt >out_py_new.txt
py -3 rope_new.py <%1\test49.txt >out_py_new.txt
py -3 rope_new.py <%1\test50.txt >out_py_new.txt
py -3 rope_new.py <%1\test51.txt >out_py_new.txt
py -3 rope_new.py <%1\test52.txt >out_py_new.txt
py -3 rope_new.py <%1\test53.txt >out_py_new.txt
py -3 rope_new.py <%1\test54.txt >out_py_new.txt
py -3 rope_new.py <%1\test55.txt >out_py_new.txt
py -3 rope_new.py <%1\test56.txt >out_py_new.txt
py -3 rope_new.py <%1\test57.txt >out_py_new.txt
py -3 rope_new.py <%1\test58.txt >out_py_new.txt
py -3 rope_new.py <%1\test59.txt >out_py_new.txt
py -3 rope_new.py <%1\test60.txt >out_py_new.txt
py -3 rope_new.py <%1\test61.txt >out_py_new.txt
py -3 rope_new.py <%1\test62.txt >out_py_new.txt
py -3 rope_new.py <%1\test63.txt >out_py_new.txt
py -3 rope_new.py <%1\test64.txt >out_py_new.txt
py -3 rope_new.py <%1\test65.txt >out_py_new.txt
py -3 rope_new.py <%1\test66.txt >out_py_new.txt
py -3 rope_new.py <%1\test67.txt >out_py_new.txt
py -3 rope_new.py <%1\test68.txt >out_py_new.txt
py -3 rope_new.py <%1\test69.txt >out_py_new.txt
py -3 rope_new.py <%1\test70.txt >out_py_new.txt
py -3 rope_new.py <%1\test71.txt >out_py_new.txt
py -3 rope_new.py <%1\test72.txt >out_py_new.txt
py -3 rope_new.py <%1\test73.txt >out_py_new.txt
py -3 rope_new.py <%1\test74.txt >out_py_new.txt
py -3 rope_new.py <%1\test75.txt >out_py_new.txt
py -3 rope_new.py <%1\test76.txt >out_py_new.txt
py -3 rope_new.py <%1\test77.txt >out_py_new.txt
py -3 rope_new.py <%1\test78.txt >out_py_new.txt
py -3 rope_new.py <%1\test79.txt >out_py_new.txt
py -3 rope_new.py <%1\test80.txt >out_py_new.txt
py -3 rope_new.py <%1\test81.txt >out_py_new.txt
py -3 rope_new.py <%1\test82.txt >out_py_new.txt
py -3 rope_new.py <%1\test83.txt >out_py_new.txt
py -3 rope_new.py <%1\test84.txt >out_py_new.txt
py -3 rope_new.py <%1\test85.txt >out_py_new.txt
py -3 rope_new.py <%1\test86.txt >out_py_new.txt
py -3 rope_new.py <%1\test87.txt >out_py_new.txt
py -3 rope_new.py <%1\test88.txt >out_py_new.txt
py -3 rope_new.py <%1\test89.txt >out_py_new.txt
py -3 rope_new.py <%1\test90.txt >out_py_new.txt
py -3 rope_new.py <%1\test91.txt >out_py_new.txt
py -3 rope_new.py <%1\test92.txt >out_py_new.txt
py -3 rope_new.py <%1\test93.txt >out_py_new.txt
py -3 rope_new.py <%1\test94.txt >out_py_new.txt
py -3 rope_new.py <%1\test95.txt >out_py_new.txt
py -3 rope_new.py <%1\test96.txt >out_py_new.txt
py -3 rope_new.py <%1\test97.txt >out_py_new.txt
py -3 rope_new.py <%1\test98.txt >out_py_new.txt
py -3 rope_new.py <%1\test99.txt >out_py_new.txt
py -3 rope_new.py <%1\test100.txt >out_py_new.txt
py -3 rope_new.py <%1\test101.txt >out_py_new.txt
py -3 rope_new.py <%1\test102.txt >out_py_new.txt
py -3 rope_new.py <%1\test103.txt >out_py_new.txt
py -3 rope_new.py <%1\test104.txt >out_py_new.txt
py -3 rope_new.py <%1\test105.txt >out_py_new.txt
py -3 rope_new.py <%1\test106.txt >out_py_new.txt
py -3 rope_new.py <%1\test107.txt >out_py_new.txt
py -3 rope_new.py <%1\test108.txt >out_py_new.txt
py -3 rope_new.py <%1\test109.txt >out_py_new.txt
py -3 rope_new.py <%1\test110.txt >out_py_new.txt
py -3 rope_new.py <%1\test111.txt >out_py_new.txt
py -3 rope_new.py <%1\test112.txt >out_py_new.txt
py -3 rope_new.py <%1\test113.txt >out_py_new.txt
py -3 rope_new.py <%1\test114.txt >out_py_new.txt
py -3 rope_new.py <%1\test115.txt >out_py_new.txt
py -3 rope_new.py <%1\test116.txt >out_py_new.txt
py -3 rope_new.py <%1\test117.txt >out_py_new.txt
py -3 rope_new.py <%1\test118.txt >out_py_new.txt
py -3 rope_new.py <%1\test119.txt >out_py_new.txt
py -3 rope_new.py <%1\test120.txt >out_py_new.txt
py -3 rope_new.py <%1\test121.txt >out_py_new.txt
py -3 rope_new.py <%1\test122.txt >out_py_new.txt
py -3 rope_new.py <%1\test123.txt >out_py_new.txt
py -3 rope_new.py <%1\test124.txt >out_py_new.txt
py -3 rope_new.py <%1\test125.txt >out_py_new.txt
py -3 rope_new.py <%1\test126.txt >out_py_new.txt
py -3 rope_new.py <%1\test127.txt >out_py_new.txt
py -3 rope_new.py <%1\test128.txt >out_py_new.txt
py -3 rope_new.py <%1\test129.txt >out_py_new.txt
py -3 rope_new.py <%1\test130.txt >out_py_new.txt
py -3 rope_new.py <%1\test131.txt >out_py_new.txt
py -3 rope_new.py <%1\test132.txt >out_py_new.txt
py -3 rope_new.py <%1\test133.txt >out_py_new.txt
py -3 rope_new.py <%1\test134.txt >out_py_new.txt
py -3 rope_new.py <%1\test135.txt >out_py_new.txt
py -3 rope_new.py <%1\test136.txt >out_py_new.txt
py -3 rope_new.py <%1\test137.txt >out_py_new.txt
py -3 rope_new.py <%1\test138.txt >out_py_new.txt
py -3 rope_new.py <%1\test139.txt >out_py_new.txt
py -3 rope_new.py <%1\test140.txt >out_py_new.txt
py -3 rope_new.py <%1\test141.txt >out_py_new.txt
py -3 rope_new.py <%1\test142.txt >out_py_new.txt
py -3 rope_new.py <%1\test143.txt >out_py_new.txt
py -3 rope_new.py <%1\test144.txt >out_py_new.txt
py -3 rope_new.py <%1\test145.txt >out_py_new.txt
py -3 rope_new.py <%1\test146.txt >out_py_new.txt
py -3 rope_new.py <%1\test147.txt >out_py_new.txt
py -3 rope_new.py <%1\test148.txt >out_py_new.txt
py -3 rope_new.py <%1\test149.txt >out_py_new.txt
py -3 rope_new.py <%1\test150.txt >out_py_new.txt
py -3 rope_new.py <%1\test151.txt >out_py_new.txt
py -3 rope_new.py <%1\test152.txt >out_py_new.txt
py -3 rope_new.py <%1\test153.txt >out_py_new.txt
py -3 rope_new.py <%1\test154.txt >out_py_new.txt
py -3 rope_new.py <%1\test155.txt >out_py_new.txt
py -3 rope_new.py <%1\test156.txt >out_py_new.txt
py -3 rope_new.py <%1\test157.txt >out_py_new.txt
py -3 rope_new.py <%1\test158.txt >out_py_new.txt
py -3 rope_new.py <%1\test159.txt >out_py_new.txt
py -3 rope_new.py <%1\test160.txt >out_py_new.txt
py -3 rope_new.py <%1\test161.txt >out_py_new.txt
py -3 rope_new.py <%1\test162.txt >out_py_new.txt
py -3 rope_new.py <%1\test163.txt >out_py_new.txt
py -3 rope_new.py <%1\test164.txt >out_py_new.txt
py -3 rope_new.py <%1\test165.txt >out_py_new.txt
py -3 rope_new.py <%1\test166.txt >out_py_new.txt
py -3 rope_new.py <%1\test167.txt >out_py_new.txt
py -3 rope_new.py <%1\test168.txt >out_py_new.txt
py -3 rope_new.py <%1\test169.txt >out_py_new.txt
py -3 rope_new.py <%1\test170.txt >out_py_new.txt
py -3 rope_new.py <%1\test171.txt >out_py_new.txt
py -3 rope_new.py <%1\test172.txt >out_py_new.txt
py -3 rope_new.py <%1\test173.txt >out_py_new.txt
py -3 rope_new.py <%1\test174.txt >out_py_new.txt
py -3 rope_new.py <%1\test175.txt >out_py_new.txt
py -3 rope_new.py <%1\test176.txt >out_py_new.txt
py -3 rope_new.py <%1\test177.txt >out_py_new.txt
py -3 rope_new.py <%1\test178.txt >out_py_new.txt
py -3 rope_new.py <%1\test179.txt >out_py_new.txt
py -3 rope_new.py <%1\test180.txt >out_py_new.txt
py -3 rope_new.py <%1\test181.txt >out_py_new.txt
py -3 rope_new.py <%1\test182.txt >out_py_new.txt
py -3 rope_new.py <%1\test183.txt >out_py_new.txt
py -3 rope_new.py <%1\test184.txt >out_py_new.txt
py -3 rope_new.py <%1\test185.txt >out_py_new.txt
py -3 rope_new.py <%1\test186.txt >out_py_new.txt
py -3 rope_new.py <%1\test187.txt >out_py_new.txt
py -3 rope_new.py <%1\test188.txt >out_py_new.txt
py -3 rope_new.py <%1\test189.txt >out_py_new.txt
py -3 rope_new.py <%1\test190.txt >out_py_new.txt
py -3 rope_new.py <%1\test191.txt >out_py_new.txt
py -3 rope_new.py <%1\test192.txt >out_py_new.txt
py -3 rope_new.py <%1\test193.txt >out_py_new.txt
py -3 rope_new.py <%1\test194.txt >out_py_new.txt
py -3 rope_new.py <%1\test195.txt >out_py_new.txt
py -3 rope_new.py <%1\test196.txt >out_py_new.txt
py -3 rope_new.py <%1\test197.txt >out_py_new.txt
py -3 rope_new.py <%1\test198.txt >out_py_new.txt
py -3 rope_new.py <%1\test199.txt >out_py_new.txt
py -3 rope_new.py <%1\test200.txt >out_py_new.txt
py -3 rope_new.py <%1\test201.txt >out_py_new.txt
py -3 rope_new.py <%1\test202.txt >out_py_new.txt
py -3 rope_new.py <%1\test203.txt >out_py_new.txt
py -3 rope_new.py <%1\test204.txt >out_py_new.txt
py -3 rope_new.py <%1\test205.txt >out_py_new.txt
py -3 rope_new.py <%1\test206.txt >out_py_new.txt
py -3 rope_new.py <%1\test207.txt >out_py_new.txt
py -3 rope_new.py <%1\test208.txt >out_py_new.txt
py -3 rope_new.py <%1\test209.txt >out_py_new.txt
py -3 rope_new.py <%1\test210.txt >out_py_new.txt
py -3 rope_new.py <%1\test211.txt >out_py_new.txt
py -3 rope_new.py <%1\test212.txt >out_py_new.txt
py -3 rope_new.py <%1\test213.txt >out_py_new.txt
py -3 rope_new.py <%1\test214.txt >out_py_new.txt
py -3 rope_new.py <%1\test215.txt >out_py_new.txt
py -3 rope_new.py <%1\test216.txt >out_py_new.txt
py -3 rope_new.py <%1\test217.txt >out_py_new.txt
py -3 rope_new.py <%1\test218.txt >out_py_new.txt
py -3 rope_new.py <%1\test219.txt >out_py_new.txt
py -3 rope_new.py <%1\test220.txt >out_py_new.txt
py -3 rope_new.py <%1\test221.txt >out_py_new.txt
py -3 rope_new.py <%1\test222.txt >out_py_new.txt
py -3 rope_new.py <%1\test223.txt >out_py_new.txt
py -3 rope_new.py <%1\test224.txt >out_py_new.txt
py -3 rope_new.py <%1\test225.txt >out_py_new.txt
py -3 rope_new.py <%1\test226.txt >out_py_new.txt
py -3 rope_new.py <%1\test227.txt >out_py_new.txt
py -3 rope_new.py <%1\test228.txt >out_py_new.txt
py -3 rope_new.py <%1\test229.txt >out_py_new.txt
py -3 rope_new.py <%1\test230.txt >out_py_new.txt
py -3 rope_new.py <%1\test231.txt >out_py_new.txt
py -3 rope_new.py <%1\test232.txt >out_py_new.txt
py -3 rope_new.py <%1\test233.txt >out_py_new.txt
py -3 rope_new.py <%1\test234.txt >out_py_new.txt
py -3 rope_new.py <%1\test235.txt >out_py_new.txt
py -3 rope_new.py <%1\test236.txt >out_py_new.txt
py -3 rope_new.py <%1\test237.txt >out_py_new.txt
py -3 rope_new.py <%1\test238.txt >out_py_new.txt
py -3 rope_new.py <%1\test239.txt >out_py_new.txt
py -3 rope_new.py <%1\test240.txt >out_py_new.txt
py -3 rope_new.py <%1\test241.txt >out_py_new.txt
py -3 rope_new.py <%1\test242.txt >out_py_new.txt
py -3 rope_new.py <%1\test243.txt >out_py_new.txt
py -3 rope_new.py <%1\test244.txt >out_py_new.txt
py -3 rope_new.py <%1\test245.txt >out_py_new.txt
py -3 rope_new.py <%1\test246.txt >out_py_new.txt
py -3 rope_new.py <%1\test247.txt >out_py_new.txt
py -3 rope_new.py <%1\test248.txt >out_py_new.txt
py -3 rope_new.py <%1\test249.txt >out_py_new.txt
py -3 rope_new.py <%1\test250.txt >out_py_new.txt
py -3 rope_new.py <%1\test251.txt >out_py_new.txt
py -3 rope_new.py <%1\test252.txt >out_py_new.txt
py -3 rope_new.py <%1\test253.txt >out_py_new.txt
py -3 rope_new.py <%1\test254.txt >out_py_new.txt
py -3 rope_new.py <%1\test255.txt >out_py_new.txt
py -3 rope_new.py <%1\test256.txt >out_py_new.txt
py -3 rope_new.py <%1\test257.txt >out_py_new.txt
py -3 rope_new.py <%1\test258.txt >out_py_new.txt
py -3 rope_new.py <%1\test259.txt >out_py_new.txt
py -3 rope_new.py <%1\test260.txt >out_py_new.txt
py -3 rope_new.py <%1\test261.txt >out_py_new.txt
py -3 rope_new.py <%1\test262.txt >out_py_new.txt
py -3 rope_new.py <%1\test263.txt >out_py_new.txt
py -3 rope_new.py <%1\test264.txt >out_py_new.txt
py -3 rope_new.py <%1\test265.txt >out_py_new.txt
py -3 rope_new.py <%1\test266.txt >out_py_new.txt
py -3 rope_new.py <%1\test267.txt >out_py_new.txt
py -3 rope_new.py <%1\test268.txt >out_py_new.txt
py -3 rope_new.py <%1\test269.txt >out_py_new.txt
py -3 rope_new.py <%1\test270.txt >out_py_new.txt
py -3 rope_new.py <%1\test271.txt >out_py_new.txt
py -3 rope_new.py <%1\test272.txt >out_py_new.txt
py -3 rope_new.py <%1\test273.txt >out_py_new.txt
py -3 rope_new.py <%1\test274.txt >out_py_new.txt
py -3 rope_new.py <%1\test275.txt >out_py_new.txt
py -3 rope_new.py <%1\test276.txt >out_py_new.txt
py -3 rope_new.py <%1\test277.txt >out_py_new.txt
py -3 rope_new.py <%1\test278.txt >out_py_new.txt
py -3 rope_new.py <%1\test279.txt >out_py_new.txt
py -3 rope_new.py <%1\test280.txt >out_py_new.txt
py -3 rope_new.py <%1\test281.txt >out_py_new.txt
py -3 rope_new.py <%1\test282.txt >out_py_new.txt
py -3 rope_new.py <%1\test283.txt >out_py_new.txt
py -3 rope_new.py <%1\test284.txt >out_py_new.txt
py -3 rope_new.py <%1\test285.txt >out_py_new.txt
py -3 rope_new.py <%1\test286.txt >out_py_new.txt
py -3 rope_new.py <%1\test287.txt >out_py_new.txt
py -3 rope_new.py <%1\test288.txt >out_py_new.txt
py -3 rope_new.py <%1\test289.txt >out_py_new.txt
py -3 rope_new.py <%1\test290.txt >out_py_new.txt
py -3 rope_new.py <%1\test291.txt >out_py_new.txt
py -3 rope_new.py <%1\test292.txt >out_py_new.txt
py -3 rope_new.py <%1\test293.txt >out_py_new.txt
py -3 rope_new.py <%1\test294.txt >out_py_new.txt
py -3 rope_new.py <%1\test295.txt >out_py_new.txt
py -3 rope_new.py <%1\test296.txt >out_py_new.txt
py -3 rope_new.py <%1\test297.txt >out_py_new.txt
py -3 rope_new.py <%1\test298.txt >out_py_new.txt
py -3 rope_new.py <%1\test299.txt >out_py_new.txt
py -3 rope_new.py <%1\test300.txt >out_py_new.txt
py -3 rope_new.py <%1\test301.txt >out_py_new.txt
py -3 rope_new.py <%1\test302.txt >out_py_new.txt
py -3 rope_new.py <%1\test303.txt >out_py_new.txt
py -3 rope_new.py <%1\test304.txt >out_py_new.txt
py -3 rope_new.py <%1\test305.txt >out_py_new.txt
py -3 rope_new.py <%1\test306.txt >out_py_new.txt
py -3 rope_new.py <%1\test307.txt >out_py_new.txt
py -3 rope_new.py <%1\test308.txt >out_py_new.txt
py -3 rope_new.py <%1\test309.txt >out_py_new.txt
py -3 rope_new.py <%1\test310.txt >out_py_new.txt
py -3 rope_new.py <%1\test311.txt >out_py_new.txt
py -3 rope_new.py <%1\test312.txt >out_py_new.txt
py -3 rope_new.py <%1\test313.txt >out_py_new.txt
py -3 rope_new.py <%1\test314.txt >out_py_new.txt
py -3 rope_new.py <%1\test315.txt >out_py_new.txt
py -3 rope_new.py <%1\test316.txt >out_py_new.txt
py -3 rope_new.py <%1\test317.txt >out_py_new.txt
py -3 rope_new.py <%1\test318.txt >out_py_new.txt
py -3 rope_new.py <%1\test319.txt >out_py_new.txt
py -3 rope_new.py <%1\test320.txt >out_py_new.txt
py -3 rope_new.py <%1\test321.txt >out_py_new.txt
py -3 rope_new.py <%1\test322.txt >out_py_new.txt
py -3 rope_new.py <%1\test323.txt >out_py_new.txt
py -3 rope_new.py <%1\test324.txt >out_py_new.txt
py -3 rope_new.py <%1\test325.txt >out_py_new.txt
py -3 rope_new.py <%1\test326.txt >out_py_new.txt
py -3 rope_new.py <%1\test327.txt >out_py_new.txt
py -3 rope_new.py <%1\test328.txt >out_py_new.txt
py -3 rope_new.py <%1\test329.txt >out_py_new.txt
py -3 rope_new.py <%1\test330.txt >out_py_new.txt
py -3 rope_new.py <%1\test331.txt >out_py_new.txt
py -3 rope_new.py <%1\test332.txt >out_py_new.txt
py -3 rope_new.py <%1\test333.txt >out_py_new.txt
py -3 rope_new.py <%1\test334.txt >out_py_new.txt
py -3 rope_new.py <%1\test335.txt >out_py_new.txt
py -3 rope_new.py <%1\test336.txt >out_py_new.txt
py -3 rope_new.py <%1\test337.txt >out_py_new.txt
py -3 rope_new.py <%1\test338.txt >out_py_new.txt
py -3 rope_new.py <%1\test339.txt >out_py_new.txt
py -3 rope_new.py <%1\test340.txt >out_py_new.txt
py -3 rope_new.py <%1\test341.txt >out_py_new.txt
py -3 rope_new.py <%1\test342.txt >out_py_new.txt
py -3 rope_new.py <%1\test343.txt >out_py_new.txt
py -3 rope_new.py <%1\test344.txt >out_py_new.txt
py -3 rope_new.py <%1\test345.txt >out_py_new.txt
py -3 rope_new.py <%1\test346.txt >out_py_new.txt
py -3 rope_new.py <%1\test347.txt >out_py_new.txt
py -3 rope_new.py <%1\test348.txt >out_py_new.txt
py -3 rope_new.py <%1\test349.txt >out_py_new.txt
py -3 rope_new.py <%1\test350.txt >out_py_new.txt
py -3 rope_new.py <%1\test351.txt >out_py_new.txt
py -3 rope_new.py <%1\test352.txt >out_py_new.txt
py -3 rope_new.py <%1\test353.txt >out_py_new.txt
py -3 rope_new.py <%1\test354.txt >out_py_new.txt
py -3 rope_new.py <%1\test355.txt >out_py_new.txt
py -3 rope_new.py <%1\test356.txt >out_py_new.txt
py -3 rope_new.py <%1\test357.txt >out_py_new.txt
py -3 rope_new.py <%1\test358.txt >out_py_new.txt
py -3 rope_new.py <%1\test359.txt >out_py_new.txt
py -3 rope_new.py <%1\test360.txt >out_py_new.txt
py -3 rope_new.py <%1\test361.txt >out_py_new.txt
py -3 rope_new.py <%1\test362.txt >out_py_new.txt
py -3 rope_new.py <%1\test363.txt >out_py_new.txt
py -3 rope_new.py <%1\test364.txt >out_py_new.txt
py -3 rope_new.py <%1\test365.txt >out_py_new.txt
py -3 rope_new.py <%1\test366.txt >out_py_new.txt
py -3 rope_new.py <%1\test367.txt >out_py_new.txt
py -3 rope_new.py <%1\test368.txt >out_py_new.txt
py -3 rope_new.py <%1\test369.txt >out_py_new.txt
py -3 rope_new.py <%1\test370.txt >out_py_new.txt
py -3 rope_new.py <%1\test371.txt >out_py_new.txt
py -3 rope_new.py <%1\test372.txt >out_py_new.txt
py -3 rope_new.py <%1\test373.txt >out_py_new.txt
py -3 rope_new.py <%1\test374.txt >out_py_new.txt
py -3 rope_new.py <%1\test375.txt >out_py_new.txt
py -3 rope_new.py <%1\test376.txt >out_py_new.txt
py -3 rope_new.py <%1\test377.txt >out_py_new.txt
py -3 rope_new.py <%1\test378.txt >out_py_new.txt
py -3 rope_new.py <%1\test379.txt >out_py_new.txt
py -3 rope_new.py <%1\test380.txt >out_py_new.txt
py -3 rope_new.py <%1\test381.txt >out_py_new.txt
py -3 rope_new.py <%1\test382.txt >out_py_new.txt
py -3 rope_new.py <%1\test383.txt >out_py_new.txt
py -3 rope_new.py <%1\test384.txt >out_py_new.txt
py -3 rope_new.py <%1\test385.txt >out_py_new.txt
py -3 rope_new.py <%1\test386.txt >out_py_new.txt
py -3 rope_new.py <%1\test387.txt >out_py_new.txt
py -3 rope_new.py <%1\test388.txt >out_py_new.txt
py -3 rope_new.py <%1\test389.txt >out_py_new.txt
py -3 rope_new.py <%1\test390.txt >out_py_new.txt
py -3 rope_new.py <%1\test391.txt >out_py_new.txt
py -3 rope_new.py <%1\test392.txt >out_py_new.txt
py -3 rope_new.py <%1\test393.txt >out_py_new.txt
py -3 rope_new.py <%1\test394.txt >out_py_new.txt
py -3 rope_new.py <%1\test395.txt >out_py_new.txt
py -3 rope_new.py <%1\test396.txt >out_py_new.txt
py -3 rope_new.py <%1\test397.txt >out_py_new.txt
py -3 rope_new.py <%1\test398.txt >out_py_new.txt
py -3 rope_new.py <%1\test399.txt >out_py_new.txt
py -3 rope_new.py <%1\test400.txt >out_py_new.txt
py -3 rope_new.py <%1\test401.txt >out_py_new.txt
py -3 rope_new.py <%1\test402.txt >out_py_new.txt
py -3 rope_new.py <%1\test403.txt >out_py_new.txt
py -3 rope_new.py <%1\test404.txt >out_py_new.txt
py -3 rope_new.py <%1\test405.txt >out_py_new.txt
py -3 rope_new.py <%1\test406.txt >out_py_new.txt
py -3 rope_new.py <%1\test407.txt >out_py_new.txt
py -3 rope_new.py <%1\test408.txt >out_py_new.txt
py -3 rope_new.py <%1\test409.txt >out_py_new.txt
py -3 rope_new.py <%1\test410.txt >out_py_new.txt
py -3 rope_new.py <%1\test411.txt >out_py_new.txt
py -3 rope_new.py <%1\test412.txt >out_py_new.txt
py -3 rope_new.py <%1\test413.txt >out_py_new.txt
py -3 rope_new.py <%1\test414.txt >out_py_new.txt
py -3 rope_new.py <%1\test415.txt >out_py_new.txt
py -3 rope_new.py <%1\test416.txt >out_py_new.txt
py -3 rope_new.py <%1\test417.txt >out_py_new.txt
py -3 rope_new.py <%1\test418.txt >out_py_new.txt
py -3 rope_new.py <%1\test419.txt >out_py_new.txt
py -3 rope_new.py <%1\test420.txt >out_py_new.txt
py -3 rope_new.py <%1\test421.txt >out_py_new.txt
py -3 rope_new.py <%1\test422.txt >out_py_new.txt
py -3 rope_new.py <%1\test423.txt >out_py_new.txt
py -3 rope_new.py <%1\test424.txt >out_py_new.txt
py -3 rope_new.py <%1\test425.txt >out_py_new.txt
py -3 rope_new.py <%1\test426.txt >out_py_new.txt
py -3 rope_new.py <%1\test427.txt >out_py_new.txt
py -3 rope_new.py <%1\test428.txt >out_py_new.txt
py -3 rope_new.py <%1\test429.txt >out_py_new.txt
py -3 rope_new.py <%1\test430.txt >out_py_new.txt
py -3 rope_new.py <%1\test431.txt >out_py_new.txt
py -3 rope_new.py <%1\test432.txt >out_py_new.txt
py -3 rope_new.py <%1\test433.txt >out_py_new.txt
py -3 rope_new.py <%1\test434.txt >out_py_new.txt
py -3 rope_new.py <%1\test435.txt >out_py_new.txt
py -3 rope_new.py <%1\test436.txt >out_py_new.txt
py -3 rope_new.py <%1\test437.txt >out_py_new.txt
py -3 rope_new.py <%1\test438.txt >out_py_new.txt
py -3 rope_new.py <%1\test439.txt >out_py_new.txt
py -3 rope_new.py <%1\test440.txt >out_py_new.txt
py -3 rope_new.py <%1\test441.txt >out_py_new.txt
py -3 rope_new.py <%1\test442.txt >out_py_new.txt
py -3 rope_new.py <%1\test443.txt >out_py_new.txt
py -3 rope_new.py <%1\test444.txt >out_py_new.txt
py -3 rope_new.py <%1\test445.txt >out_py_new.txt
py -3 rope_new.py <%1\test446.txt >out_py_new.txt
py -3 rope_new.py <%1\test447.txt >out_py_new.txt
py -3 rope_new.py <%1\test448.txt >out_py_new.txt
py -3 rope_new.py <%1\test449.txt >out_py_new.txt
py -3 rope_new.py <%1\test450.txt >out_py_new.txt
py -3 rope_new.py <%1\test451.txt >out_py_new.txt
py -3 rope_new.py <%1\test452.txt >out_py_new.txt
py -3 rope_new.py <%1\test453.txt >out_py_new.txt
py -3 rope_new.py <%1\test454.txt >out_py_new.txt
py -3 rope_new.py <%1\test455.txt >out_py_new.txt
py -3 rope_new.py <%1\test456.txt >out_py_new.txt
py -3 rope_new.py <%1\test457.txt >out_py_new.txt
py -3 rope_new.py <%1\test458.txt >out_py_new.txt
py -3 rope_new.py <%1\test459.txt >out_py_new.txt
py -3 rope_new.py <%1\test460.txt >out_py_new.txt
py -3 rope_new.py <%1\test461.txt >out_py_new.txt
py -3 rope_new.py <%1\test462.txt >out_py_new.txt
py -3 rope_new.py <%1\test463.txt >out_py_new.txt
py -3 rope_new.py <%1\test464.txt >out_py_new.txt
py -3 rope_new.py <%1\test465.txt >out_py_new.txt
py -3 rope_new.py <%1\test466.txt >out_py_new.txt
py -3 rope_new.py <%1\test467.txt >out_py_new.txt
py -3 rope_new.py <%1\test468.txt >out_py_new.txt
py -3 rope_new.py <%1\test469.txt >out_py_new.txt
py -3 rope_new.py <%1\test470.txt >out_py_new.txt
py -3 rope_new.py <%1\test471.txt >out_py_new.txt
py -3 rope_new.py <%1\test472.txt >out_py_new.txt
py -3 rope_new.py <%1\test473.txt >out_py_new.txt
py -3 rope_new.py <%1\test474.txt >out_py_new.txt
py -3 rope_new.py <%1\test475.txt >out_py_new.txt
py -3 rope_new.py <%1\test476.txt >out_py_new.txt
py -3 rope_new.py <%1\test477.txt >out_py_new.txt
py -3 rope_new.py <%1\test478.txt >out_py_new.txt
py -3 rope_new.py <%1\test479.txt >out_py_new.txt
py -3 rope_new.py <%1\test480.txt >out_py_new.txt
py -3 rope_new.py <%1\test481.txt >out_py_new.txt
py -3 rope_new.py <%1\test482.txt >out_py_new.txt
py -3 rope_new.py <%1\test483.txt >out_py_new.txt
py -3 rope_new.py <%1\test484.txt >out_py_new.txt
py -3 rope_new.py <%1\test485.txt >out_py_new.txt
py -3 rope_new.py <%1\test486.txt >out_py_new.txt
py -3 rope_new.py <%1\test487.txt >out_py_new.txt
py -3 rope_new.py <%1\test488.txt >out_py_new.txt
py -3 rope_new.py <%1\test489.txt >out_py_new.txt
py -3 rope_new.py <%1\test490.txt >out_py_new.txt
py -3 rope_new.py <%1\test491.txt >out_py_new.txt
py -3 rope_new.py <%1\test492.txt >out_py_new.txt
py -3 rope_new.py <%1\test493.txt >out_py_new.txt
py -3 rope_new.py <%1\test494.txt >out_py_new.txt
py -3 rope_new.py <%1\test495.txt >out_py_new.txt
py -3 rope_new.py <%1\test496.txt >out_py_new.txt
py -3 rope_new.py <%1\test497.txt >out_py_new.txt
py -3 rope_new.py <%1\test498.txt >out_py_new.txt
py -3 rope_new.py <%1\test499.txt >out_py_new.txt
py -3 rope_new.py <%1\test500.txt >out_py_new.txt
py -3 rope_new.py <%1\test501.txt >out_py_new.txt
py -3 rope_new.py <%1\test502.txt >out_py_new.txt
py -3 rope_new.py <%1\test503.txt >out_py_new.txt
py -3 rope_new.py <%1\test504.txt >out_py_new.txt
py -3 rope_new.py <%1\test505.txt >out_py_new.txt
py -3 rope_new.py <%1\test506.txt >out_py_new.txt
py -3 rope_new.py <%1\test507.txt >out_py_new.txt
py -3 rope_new.py <%1\test508.txt >out_py_new.txt
py -3 rope_new.py <%1\test509.txt >out_py_new.txt
py -3 rope_new.py <%1\test510.txt >out_py_new.txt
py -3 rope_new.py <%1\test511.txt >out_py_new.txt
py -3 rope_new.py <%1\test512.txt >out_py_new.txt
py -3 rope_new.py <%1\test513.txt >out_py_new.txt
py -3 rope_new.py <%1\test514.txt >out_py_new.txt
py -3 rope_new.py <%1\test515.txt >out_py_new.txt
py -3 rope_new.py <%1\test516.txt >out_py_new.txt
py -3 rope_new.py <%1\test517.txt >out_py_new.txt
py -3 rope_new.py <%1\test518.txt >out_py_new.txt
py -3 rope_new.py <%1\test519.txt >out_py_new.txt
py -3 rope_new.py <%1\test520.txt >out_py_new.txt
py -3 rope_new.py <%1\test521.txt >out_py_new.txt
py -3 rope_new.py <%1\test522.txt >out_py_new.txt
py -3 rope_new.py <%1\test523.txt >out_py_new.txt
py -3 rope_new.py <%1\test524.txt >out_py_new.txt
py -3 rope_new.py <%1\test525.txt >out_py_new.txt
py -3 rope_new.py <%1\test526.txt >out_py_new.txt
py -3 rope_new.py <%1\test527.txt >out_py_new.txt
py -3 rope_new.py <%1\test528.txt >out_py_new.txt
py -3 rope_new.py <%1\test529.txt >out_py_new.txt
py -3 rope_new.py <%1\test530.txt >out_py_new.txt
py -3 rope_new.py <%1\test531.txt >out_py_new.txt
py -3 rope_new.py <%1\test532.txt >out_py_new.txt
py -3 rope_new.py <%1\test533.txt >out_py_new.txt
py -3 rope_new.py <%1\test534.txt >out_py_new.txt
py -3 rope_new.py <%1\test535.txt >out_py_new.txt
py -3 rope_new.py <%1\test536.txt >out_py_new.txt
py -3 rope_new.py <%1\test537.txt >out_py_new.txt
py -3 rope_new.py <%1\test538.txt >out_py_new.txt
py -3 rope_new.py <%1\test539.txt >out_py_new.txt
py -3 rope_new.py <%1\test540.txt >out_py_new.txt
py -3 rope_new.py <%1\test541.txt >out_py_new.txt
py -3 rope_new.py <%1\test542.txt >out_py_new.txt
py -3 rope_new.py <%1\test543.txt >out_py_new.txt
py -3 rope_new.py <%1\test544.txt >out_py_new.txt
py -3 rope_new.py <%1\test545.txt >out_py_new.txt
py -3 rope_new.py <%1\test546.txt >out_py_new.txt
py -3 rope_new.py <%1\test547.txt >out_py_new.txt
py -3 rope_new.py <%1\test548.txt >out_py_new.txt
py -3 rope_new.py <%1\test549.txt >out_py_new.txt
py -3 rope_new.py <%1\test550.txt >out_py_new.txt
py -3 rope_new.py <%1\test551.txt >out_py_new.txt
py -3 rope_new.py <%1\test552.txt >out_py_new.txt
py -3 rope_new.py <%1\test553.txt >out_py_new.txt
py -3 rope_new.py <%1\test554.txt >out_py_new.txt
py -3 rope_new.py <%1\test555.txt >out_py_new.txt
py -3 rope_new.py <%1\test556.txt >out_py_new.txt
py -3 rope_new.py <%1\test557.txt >out_py_new.txt
py -3 rope_new.py <%1\test558.txt >out_py_new.txt
py -3 rope_new.py <%1\test559.txt >out_py_new.txt
py -3 rope_new.py <%1\test560.txt >out_py_new.txt
py -3 rope_new.py <%1\test561.txt >out_py_new.txt
py -3 rope_new.py <%1\test562.txt >out_py_new.txt
py -3 rope_new.py <%1\test563.txt >out_py_new.txt
py -3 rope_new.py <%1\test564.txt >out_py_new.txt
py -3 rope_new.py <%1\test565.txt >out_py_new.txt
py -3 rope_new.py <%1\test566.txt >out_py_new.txt
py -3 rope_new.py <%1\test567.txt >out_py_new.txt
py -3 rope_new.py <%1\test568.txt >out_py_new.txt
py -3 rope_new.py <%1\test569.txt >out_py_new.txt
py -3 rope_new.py <%1\test570.txt >out_py_new.txt
py -3 rope_new.py <%1\test571.txt >out_py_new.txt
py -3 rope_new.py <%1\test572.txt >out_py_new.txt
py -3 rope_new.py <%1\test573.txt >out_py_new.txt
py -3 rope_new.py <%1\test574.txt >out_py_new.txt
py -3 rope_new.py <%1\test575.txt >out_py_new.txt
py -3 rope_new.py <%1\test576.txt >out_py_new.txt
py -3 rope_new.py <%1\test577.txt >out_py_new.txt
py -3 rope_new.py <%1\test578.txt >out_py_new.txt
py -3 rope_new.py <%1\test579.txt >out_py_new.txt
py -3 rope_new.py <%1\test580.txt >out_py_new.txt
py -3 rope_new.py <%1\test581.txt >out_py_new.txt
py -3 rope_new.py <%1\test582.txt >out_py_new.txt
py -3 rope_new.py <%1\test583.txt >out_py_new.txt
py -3 rope_new.py <%1\test584.txt >out_py_new.txt
py -3 rope_new.py <%1\test585.txt >out_py_new.txt
py -3 rope_new.py <%1\test586.txt >out_py_new.txt
py -3 rope_new.py <%1\test587.txt >out_py_new.txt
py -3 rope_new.py <%1\test588.txt >out_py_new.txt
py -3 rope_new.py <%1\test589.txt >out_py_new.txt
py -3 rope_new.py <%1\test590.txt >out_py_new.txt
py -3 rope_new.py <%1\test591.txt >out_py_new.txt
py -3 rope_new.py <%1\test592.txt >out_py_new.txt
py -3 rope_new.py <%1\test593.txt >out_py_new.txt
py -3 rope_new.py <%1\test594.txt >out_py_new.txt
py -3 rope_new.py <%1\test595.txt >out_py_new.txt
py -3 rope_new.py <%1\test596.txt >out_py_new.txt
py -3 rope_new.py <%1\test597.txt >out_py_new.txt
py -3 rope_new.py <%1\test598.txt >out_py_new.txt
py -3 rope_new.py <%1\test599.txt >out_py_new.txt
py -3 rope_new.py <%1\test600.txt >out_py_new.txt
py -3 rope_new.py <%1\test601.txt >out_py_new.txt
py -3 rope_new.py <%1\test602.txt >out_py_new.txt
py -3 rope_new.py <%1\test603.txt >out_py_new.txt
py -3 rope_new.py <%1\test604.txt >out_py_new.txt
py -3 rope_new.py <%1\test605.txt >out_py_new.txt
py -3 rope_new.py <%1\test606.txt >out_py_new.txt
py -3 rope_new.py <%1\test607.txt >out_py_new.txt
py -3 rope_new.py <%1\test608.txt >out_py_new.txt
py -3 rope_new.py <%1\test609.txt >out_py_new.txt
py -3 rope_new.py <%1\test610.txt >out_py_new.txt
py -3 rope_new.py <%1\test611.txt >out_py_new.txt
py -3 rope_new.py <%1\test612.txt >out_py_new.txt
py -3 rope_new.py <%1\test613.txt >out_py_new.txt
py -3 rope_new.py <%1\test614.txt >out_py_new.txt
py -3 rope_new.py <%1\test615.txt >out_py_new.txt
py -3 rope_new.py <%1\test616.txt >out_py_new.txt
py -3 rope_new.py <%1\test617.txt >out_py_new.txt
py -3 rope_new.py <%1\test618.txt >out_py_new.txt
py -3 rope_new.py <%1\test619.txt >out_py_new.txt
py -3 rope_new.py <%1\test620.txt >out_py_new.txt
py -3 rope_new.py <%1\test621.txt >out_py_new.txt
py -3 rope_new.py <%1\test622.txt >out_py_new.txt
py -3 rope_new.py <%1\test623.txt >out_py_new.txt
py -3 rope_new.py <%1\test624.txt >out_py_new.txt
py -3 rope_new.py <%1\test625.txt >out_py_new.txt
py -3 rope_new.py <%1\test626.txt >out_py_new.txt
py -3 rope_new.py <%1\test627.txt >out_py_new.txt
py -3 rope_new.py <%1\test628.txt >out_py_new.txt
py -3 rope_new.py <%1\test629.txt >out_py_new.txt
py -3 rope_new.py <%1\test630.txt >out_py_new.txt
py -3 rope_new.py <%1\test631.txt >out_py_new.txt
py -3 rope_new.py <%1\test632.txt >out_py_new.txt
py -3 rope_new.py <%1\test633.txt >out_py_new.txt
py -3 rope_new.py <%1\test634.txt >out_py_new.txt
py -3 rope_new.py <%1\test635.txt >out_py_new.txt
py -3 rope_new.py <%1\test636.txt >out_py_new.txt
py -3 rope_new.py <%1\test637.txt >out_py_new.txt
py -3 rope_new.py <%1\test638.txt >out_py_new.txt
py -3 rope_new.py <%1\test639.txt >out_py_new.txt
py -3 rope_new.py <%1\test640.txt >out_py_new.txt
py -3 rope_new.py <%1\test641.txt >out_py_new.txt
py -3 rope_new.py <%1\test642.txt >out_py_new.txt
py -3 rope_new.py <%1\test643.txt >out_py_new.txt
py -3 rope_new.py <%1\test644.txt >out_py_new.txt
py -3 rope_new.py <%1\test645.txt >out_py_new.txt
py -3 rope_new.py <%1\test646.txt >out_py_new.txt
py -3 rope_new.py <%1\test647.txt >out_py_new.txt
py -3 rope_new.py <%1\test648.txt >out_py_new.txt
py -3 rope_new.py <%1\test649.txt >out_py_new.txt
py -3 rope_new.py <%1\test650.txt >out_py_new.txt
py -3 rope_new.py <%1\test651.txt >out_py_new.txt
py -3 rope_new.py <%1\test652.txt >out_py_new.txt
py -3 rope_new.py <%1\test653.txt >out_py_new.txt
py -3 rope_new.py <%1\test654.txt >out_py_new.txt
py -3 rope_new.py <%1\test655.txt >out_py_new.txt
py -3 rope_new.py <%1\test656.txt >out_py_new.txt
py -3 rope_new.py <%1\test657.txt >out_py_new.txt
py -3 rope_new.py <%1\test658.txt >out_py_new.txt
py -3 rope_new.py <%1\test659.txt >out_py_new.txt
py -3 rope_new.py <%1\test660.txt >out_py_new.txt
py -3 rope_new.py <%1\test661.txt >out_py_new.txt
py -3 rope_new.py <%1\test662.txt >out_py_new.txt
py -3 rope_new.py <%1\test663.txt >out_py_new.txt
py -3 rope_new.py <%1\test664.txt >out_py_new.txt
py -3 rope_new.py <%1\test665.txt >out_py_new.txt
py -3 rope_new.py <%1\test666.txt >out_py_new.txt
py -3 rope_new.py <%1\test667.txt >out_py_new.txt
py -3 rope_new.py <%1\test668.txt >out_py_new.txt
py -3 rope_new.py <%1\test669.txt >out_py_new.txt
py -3 rope_new.py <%1\test670.txt >out_py_new.txt
py -3 rope_new.py <%1\test671.txt >out_py_new.txt
py -3 rope_new.py <%1\test672.txt >out_py_new.txt
py -3 rope_new.py <%1\test673.txt >out_py_new.txt
py -3 rope_new.py <%1\test674.txt >out_py_new.txt
py -3 rope_new.py <%1\test675.txt >out_py_new.txt
py -3 rope_new.py <%1\test676.txt >out_py_new.txt
py -3 rope_new.py <%1\test677.txt >out_py_new.txt
py -3 rope_new.py <%1\test678.txt >out_py_new.txt
py -3 rope_new.py <%1\test679.txt >out_py_new.txt
py -3 rope_new.py <%1\test680.txt >out_py_new.txt
py -3 rope_new.py <%1\test681.txt >out_py_new.txt
py -3 rope_new.py <%1\test682.txt >out_py_new.txt
py -3 rope_new.py <%1\test683.txt >out_py_new.txt
py -3 rope_new.py <%1\test684.txt >out_py_new.txt
py -3 rope_new.py <%1\test685.txt >out_py_new.txt
py -3 rope_new.py <%1\test686.txt >out_py_new.txt
py -3 rope_new.py <%1\test687.txt >out_py_new.txt
py -3 rope_new.py <%1\test688.txt >out_py_new.txt
py -3 rope_new.py <%1\test689.txt >out_py_new.txt
py -3 rope_new.py <%1\test690.txt >out_py_new.txt
py -3 rope_new.py <%1\test691.txt >out_py_new.txt
py -3 rope_new.py <%1\test692.txt >out_py_new.txt
py -3 rope_new.py <%1\test693.txt >out_py_new.txt
py -3 rope_new.py <%1\test694.txt >out_py_new.txt
py -3 rope_new.py <%1\test695.txt >out_py_new.txt
py -3 rope_new.py <%1\test696.txt >out_py_new.txt
py -3 rope_new.py <%1\test697.txt >out_py_new.txt
py -3 rope_new.py <%1\test698.txt >out_py_new.txt
py -3 rope_new.py <%1\test699.txt >out_py_new.txt
py -3 rope_new.py <%1\test700.txt >out_py_new.txt
py -3 rope_new.py <%1\test701.txt >out_py_new.txt
py -3 rope_new.py <%1\test702.txt >out_py_new.txt
py -3 rope_new.py <%1\test703.txt >out_py_new.txt
py -3 rope_new.py <%1\test704.txt >out_py_new.txt
py -3 rope_new.py <%1\test705.txt >out_py_new.txt
py -3 rope_new.py <%1\test706.txt >out_py_new.txt
py -3 rope_new.py <%1\test707.txt >out_py_new.txt
py -3 rope_new.py <%1\test708.txt >out_py_new.txt
py -3 rope_new.py <%1\test709.txt >out_py_new.txt
py -3 rope_new.py <%1\test710.txt >out_py_new.txt
py -3 rope_new.py <%1\test711.txt >out_py_new.txt
py -3 rope_new.py <%1\test712.txt >out_py_new.txt
py -3 rope_new.py <%1\test713.txt >out_py_new.txt
py -3 rope_new.py <%1\test714.txt >out_py_new.txt
py -3 rope_new.py <%1\test715.txt >out_py_new.txt
py -3 rope_new.py <%1\test716.txt >out_py_new.txt
py -3 rope_new.py <%1\test717.txt >out_py_new.txt
py -3 rope_new.py <%1\test718.txt >out_py_new.txt
py -3 rope_new.py <%1\test719.txt >out_py_new.txt
py -3 rope_new.py <%1\test720.txt >out_py_new.txt
py -3 rope_new.py <%1\test721.txt >out_py_new.txt
py -3 rope_new.py <%1\test722.txt >out_py_new.txt
py -3 rope_new.py <%1\test723.txt >out_py_new.txt
py -3 rope_new.py <%1\test724.txt >out_py_new.txt
py -3 rope_new.py <%1\test725.txt >out_py_new.txt
py -3 rope_new.py <%1\test726.txt >out_py_new.txt
py -3 rope_new.py <%1\test727.txt >out_py_new.txt
py -3 rope_new.py <%1\test728.txt >out_py_new.txt
py -3 rope_new.py <%1\test729.txt >out_py_new.txt
py -3 rope_new.py <%1\test730.txt >out_py_new.txt
py -3 rope_new.py <%1\test731.txt >out_py_new.txt
py -3 rope_new.py <%1\test732.txt >out_py_new.txt
py -3 rope_new.py <%1\test733.txt >out_py_new.txt
py -3 rope_new.py <%1\test734.txt >out_py_new.txt
py -3 rope_new.py <%1\test735.txt >out_py_new.txt
py -3 rope_new.py <%1\test736.txt >out_py_new.txt
py -3 rope_new.py <%1\test737.txt >out_py_new.txt
py -3 rope_new.py <%1\test738.txt >out_py_new.txt
py -3 rope_new.py <%1\test739.txt >out_py_new.txt
py -3 rope_new.py <%1\test740.txt >out_py_new.txt
py -3 rope_new.py <%1\test741.txt >out_py_new.txt
py -3 rope_new.py <%1\test742.txt >out_py_new.txt
py -3 rope_new.py <%1\test743.txt >out_py_new.txt
py -3 rope_new.py <%1\test744.txt >out_py_new.txt
py -3 rope_new.py <%1\test745.txt >out_py_new.txt
py -3 rope_new.py <%1\test746.txt >out_py_new.txt
py -3 rope_new.py <%1\test747.txt >out_py_new.txt
py -3 rope_new.py <%1\test748.txt >out_py_new.txt
py -3 rope_new.py <%1\test749.txt >out_py_new.txt
py -3 rope_new.py <%1\test750.txt >out_py_new.txt
py -3 rope_new.py <%1\test751.txt >out_py_new.txt
py -3 rope_new.py <%1\test752.txt >out_py_new.txt
py -3 rope_new.py <%1\test753.txt >out_py_new.txt
py -3 rope_new.py <%1\test754.txt >out_py_new.txt
py -3 rope_new.py <%1\test755.txt >out_py_new.txt
py -3 rope_new.py <%1\test756.txt >out_py_new.txt
py -3 rope_new.py <%1\test757.txt >out_py_new.txt
py -3 rope_new.py <%1\test758.txt >out_py_new.txt
py -3 rope_new.py <%1\test759.txt >out_py_new.txt
py -3 rope_new.py <%1\test760.txt >out_py_new.txt
py -3 rope_new.py <%1\test761.txt >out_py_new.txt
py -3 rope_new.py <%1\test762.txt >out_py_new.txt
py -3 rope_new.py <%1\test763.txt >out_py_new.txt
py -3 rope_new.py <%1\test764.txt >out_py_new.txt
py -3 rope_new.py <%1\test765.txt >out_py_new.txt
py -3 rope_new.py <%1\test766.txt >out_py_new.txt
py -3 rope_new.py <%1\test767.txt >out_py_new.txt
py -3 rope_new.py <%1\test768.txt >out_py_new.txt
py -3 rope_new.py <%1\test769.txt >out_py_new.txt
py -3 rope_new.py <%1\test770.txt >out_py_new.txt
py -3 rope_new.py <%1\test771.txt >out_py_new.txt
py -3 rope_new.py <%1\test772.txt >out_py_new.txt
py -3 rope_new.py <%1\test773.txt >out_py_new.txt
py -3 rope_new.py <%1\test774.txt >out_py_new.txt
py -3 rope_new.py <%1\test775.txt >out_py_new.txt
py -3 rope_new.py <%1\test776.txt >out_py_new.txt
py -3 rope_new.py <%1\test777.txt >out_py_new.txt
py -3 rope_new.py <%1\test778.txt >out_py_new.txt
py -3 rope_new.py <%1\test779.txt >out_py_new.txt
py -3 rope_new.py <%1\test780.txt >out_py_new.txt
py -3 rope_new.py <%1\test781.txt >out_py_new.txt
py -3 rope_new.py <%1\test782.txt >out_py_new.txt
py -3 rope_new.py <%1\test783.txt >out_py_new.txt
py -3 rope_new.py <%1\test784.txt >out_py_new.txt
py -3 rope_new.py <%1\test785.txt >out_py_new.txt
py -3 rope_new.py <%1\test786.txt >out_py_new.txt
py -3 rope_new.py <%1\test787.txt >out_py_new.txt
py -3 rope_new.py <%1\test788.txt >out_py_new.txt
py -3 rope_new.py <%1\test789.txt >out_py_new.txt
py -3 rope_new.py <%1\test790.txt >out_py_new.txt
py -3 rope_new.py <%1\test791.txt >out_py_new.txt
py -3 rope_new.py <%1\test792.txt >out_py_new.txt
py -3 rope_new.py <%1\test793.txt >out_py_new.txt
py -3 rope_new.py <%1\test794.txt >out_py_new.txt
py -3 rope_new.py <%1\test795.txt >out_py_new.txt
py -3 rope_new.py <%1\test796.txt >out_py_new.txt
py -3 rope_new.py <%1\test797.txt >out_py_new.txt
py -3 rope_new.py <%1\test798.txt >out_py_new.txt
py -3 rope_new.py <%1\test799.txt >out_py_new.txt
py -3 rope_new.py <%1\test800.txt >out_py_new.txt
py -3 rope_new.py <%1\test801.txt >out_py_new.txt
py -3 rope_new.py <%1\test802.txt >out_py_new.txt
py -3 rope_new.py <%1\test803.txt >out_py_new.txt
py -3 rope_new.py <%1\test804.txt >out_py_new.txt
py -3 rope_new.py <%1\test805.txt >out_py_new.txt
py -3 rope_new.py <%1\test806.txt >out_py_new.txt
py -3 rope_new.py <%1\test807.txt >out_py_new.txt
py -3 rope_new.py <%1\test808.txt >out_py_new.txt
py -3 rope_new.py <%1\test809.txt >out_py_new.txt
py -3 rope_new.py <%1\test810.txt >out_py_new.txt
py -3 rope_new.py <%1\test811.txt >out_py_new.txt
py -3 rope_new.py <%1\test812.txt >out_py_new.txt
py -3 rope_new.py <%1\test813.txt >out_py_new.txt
py -3 rope_new.py <%1\test814.txt >out_py_new.txt
py -3 rope_new.py <%1\test815.txt >out_py_new.txt
py -3 rope_new.py <%1\test816.txt >out_py_new.txt
py -3 rope_new.py <%1\test817.txt >out_py_new.txt
py -3 rope_new.py <%1\test818.txt >out_py_new.txt
py -3 rope_new.py <%1\test819.txt >out_py_new.txt
py -3 rope_new.py <%1\test820.txt >out_py_new.txt
py -3 rope_new.py <%1\test821.txt >out_py_new.txt
py -3 rope_new.py <%1\test822.txt >out_py_new.txt
py -3 rope_new.py <%1\test823.txt >out_py_new.txt
py -3 rope_new.py <%1\test824.txt >out_py_new.txt
py -3 rope_new.py <%1\test825.txt >out_py_new.txt
py -3 rope_new.py <%1\test826.txt >out_py_new.txt
py -3 rope_new.py <%1\test827.txt >out_py_new.txt
py -3 rope_new.py <%1\test828.txt >out_py_new.txt
py -3 rope_new.py <%1\test829.txt >out_py_new.txt
py -3 rope_new.py <%1\test830.txt >out_py_new.txt
py -3 rope_new.py <%1\test831.txt >out_py_new.txt
py -3 rope_new.py <%1\test832.txt >out_py_new.txt
py -3 rope_new.py <%1\test833.txt >out_py_new.txt
py -3 rope_new.py <%1\test834.txt >out_py_new.txt
py -3 rope_new.py <%1\test835.txt >out_py_new.txt
py -3 rope_new.py <%1\test836.txt >out_py_new.txt
py -3 rope_new.py <%1\test837.txt >out_py_new.txt
py -3 rope_new.py <%1\test838.txt >out_py_new.txt
py -3 rope_new.py <%1\test839.txt >out_py_new.txt
py -3 rope_new.py <%1\test840.txt >out_py_new.txt
py -3 rope_new.py <%1\test841.txt >out_py_new.txt
py -3 rope_new.py <%1\test842.txt >out_py_new.txt
py -3 rope_new.py <%1\test843.txt >out_py_new.txt
py -3 rope_new.py <%1\test844.txt >out_py_new.txt
py -3 rope_new.py <%1\test845.txt >out_py_new.txt
py -3 rope_new.py <%1\test846.txt >out_py_new.txt
py -3 rope_new.py <%1\test847.txt >out_py_new.txt
py -3 rope_new.py <%1\test848.txt >out_py_new.txt
py -3 rope_new.py <%1\test849.txt >out_py_new.txt
py -3 rope_new.py <%1\test850.txt >out_py_new.txt
py -3 rope_new.py <%1\test851.txt >out_py_new.txt
py -3 rope_new.py <%1\test852.txt >out_py_new.txt
py -3 rope_new.py <%1\test853.txt >out_py_new.txt
py -3 rope_new.py <%1\test854.txt >out_py_new.txt
py -3 rope_new.py <%1\test855.txt >out_py_new.txt
py -3 rope_new.py <%1\test856.txt >out_py_new.txt
py -3 rope_new.py <%1\test857.txt >out_py_new.txt
py -3 rope_new.py <%1\test858.txt >out_py_new.txt
py -3 rope_new.py <%1\test859.txt >out_py_new.txt
py -3 rope_new.py <%1\test860.txt >out_py_new.txt
py -3 rope_new.py <%1\test861.txt >out_py_new.txt
py -3 rope_new.py <%1\test862.txt >out_py_new.txt
py -3 rope_new.py <%1\test863.txt >out_py_new.txt
py -3 rope_new.py <%1\test864.txt >out_py_new.txt
py -3 rope_new.py <%1\test865.txt >out_py_new.txt
py -3 rope_new.py <%1\test866.txt >out_py_new.txt
py -3 rope_new.py <%1\test867.txt >out_py_new.txt
py -3 rope_new.py <%1\test868.txt >out_py_new.txt
py -3 rope_new.py <%1\test869.txt >out_py_new.txt
py -3 rope_new.py <%1\test870.txt >out_py_new.txt
py -3 rope_new.py <%1\test871.txt >out_py_new.txt
py -3 rope_new.py <%1\test872.txt >out_py_new.txt
py -3 rope_new.py <%1\test873.txt >out_py_new.txt
py -3 rope_new.py <%1\test874.txt >out_py_new.txt
py -3 rope_new.py <%1\test875.txt >out_py_new.txt
py -3 rope_new.py <%1\test876.txt >out_py_new.txt
py -3 rope_new.py <%1\test877.txt >out_py_new.txt
py -3 rope_new.py <%1\test878.txt >out_py_new.txt
py -3 rope_new.py <%1\test879.txt >out_py_new.txt
py -3 rope_new.py <%1\test880.txt >out_py_new.txt
py -3 rope_new.py <%1\test881.txt >out_py_new.txt
py -3 rope_new.py <%1\test882.txt >out_py_new.txt
py -3 rope_new.py <%1\test883.txt >out_py_new.txt
py -3 rope_new.py <%1\test884.txt >out_py_new.txt
py -3 rope_new.py <%1\test885.txt >out_py_new.txt
py -3 rope_new.py <%1\test886.txt >out_py_new.txt
py -3 rope_new.py <%1\test887.txt >out_py_new.txt
py -3 rope_new.py <%1\test888.txt >out_py_new.txt
py -3 rope_new.py <%1\test889.txt >out_py_new.txt
py -3 rope_new.py <%1\test890.txt >out_py_new.txt
py -3 rope_new.py <%1\test891.txt >out_py_new.txt
py -3 rope_new.py <%1\test892.txt >out_py_new.txt
py -3 rope_new.py <%1\test893.txt >out_py_new.txt
py -3 rope_new.py <%1\test894.txt >out_py_new.txt
py -3 rope_new.py <%1\test895.txt >out_py_new.txt
py -3 rope_new.py <%1\test896.txt >out_py_new.txt
py -3 rope_new.py <%1\test897.txt >out_py_new.txt
py -3 rope_new.py <%1\test898.txt >out_py_new.txt
py -3 rope_new.py <%1\test899.txt >out_py_new.txt
py -3 rope_new.py <%1\test900.txt >out_py_new.txt
py -3 rope_new.py <%1\test901.txt >out_py_new.txt
py -3 rope_new.py <%1\test902.txt >out_py_new.txt
py -3 rope_new.py <%1\test903.txt >out_py_new.txt
py -3 rope_new.py <%1\test904.txt >out_py_new.txt
py -3 rope_new.py <%1\test905.txt >out_py_new.txt
py -3 rope_new.py <%1\test906.txt >out_py_new.txt
py -3 rope_new.py <%1\test907.txt >out_py_new.txt
py -3 rope_new.py <%1\test908.txt >out_py_new.txt
py -3 rope_new.py <%1\test909.txt >out_py_new.txt
py -3 rope_new.py <%1\test910.txt >out_py_new.txt
py -3 rope_new.py <%1\test911.txt >out_py_new.txt
py -3 rope_new.py <%1\test912.txt >out_py_new.txt
py -3 rope_new.py <%1\test913.txt >out_py_new.txt
py -3 rope_new.py <%1\test914.txt >out_py_new.txt
py -3 rope_new.py <%1\test915.txt >out_py_new.txt
py -3 rope_new.py <%1\test916.txt >out_py_new.txt
py -3 rope_new.py <%1\test917.txt >out_py_new.txt
py -3 rope_new.py <%1\test918.txt >out_py_new.txt
py -3 rope_new.py <%1\test919.txt >out_py_new.txt
py -3 rope_new.py <%1\test920.txt >out_py_new.txt
py -3 rope_new.py <%1\test921.txt >out_py_new.txt
py -3 rope_new.py <%1\test922.txt >out_py_new.txt
py -3 rope_new.py <%1\test923.txt >out_py_new.txt
py -3 rope_new.py <%1\test924.txt >out_py_new.txt
py -3 rope_new.py <%1\test925.txt >out_py_new.txt
py -3 rope_new.py <%1\test926.txt >out_py_new.txt
py -3 rope_new.py <%1\test927.txt >out_py_new.txt
py -3 rope_new.py <%1\test928.txt >out_py_new.txt
py -3 rope_new.py <%1\test929.txt >out_py_new.txt
py -3 rope_new.py <%1\test930.txt >out_py_new.txt
py -3 rope_new.py <%1\test931.txt >out_py_new.txt
py -3 rope_new.py <%1\test932.txt >out_py_new.txt
py -3 rope_new.py <%1\test933.txt >out_py_new.txt
py -3 rope_new.py <%1\test934.txt >out_py_new.txt
py -3 rope_new.py <%1\test935.txt >out_py_new.txt
py -3 rope_new.py <%1\test936.txt >out_py_new.txt
py -3 rope_new.py <%1\test937.txt >out_py_new.txt
py -3 rope_new.py <%1\test938.txt >out_py_new.txt
py -3 rope_new.py <%1\test939.txt >out_py_new.txt
py -3 rope_new.py <%1\test940.txt >out_py_new.txt
py -3 rope_new.py <%1\test941.txt >out_py_new.txt
py -3 rope_new.py <%1\test942.txt >out_py_new.txt
py -3 rope_new.py <%1\test943.txt >out_py_new.txt
py -3 rope_new.py <%1\test944.txt >out_py_new.txt
py -3 rope_new.py <%1\test945.txt >out_py_new.txt
py -3 rope_new.py <%1\test946.txt >out_py_new.txt
py -3 rope_new.py <%1\test947.txt >out_py_new.txt
py -3 rope_new.py <%1\test948.txt >out_py_new.txt
py -3 rope_new.py <%1\test949.txt >out_py_new.txt
py -3 rope_new.py <%1\test950.txt >out_py_new.txt
py -3 rope_new.py <%1\test951.txt >out_py_new.txt
py -3 rope_new.py <%1\test952.txt >out_py_new.txt
py -3 rope_new.py <%1\test953.txt >out_py_new.txt
py -3 rope_new.py <%1\test954.txt >out_py_new.txt
py -3 rope_new.py <%1\test955.txt >out_py_new.txt
py -3 rope_new.py <%1\test956.txt >out_py_new.txt
py -3 rope_new.py <%1\test957.txt >out_py_new.txt
py -3 rope_new.py <%1\test958.txt >out_py_new.txt
py -3 rope_new.py <%1\test959.txt >out_py_new.txt
py -3 rope_new.py <%1\test960.txt >out_py_new.txt
py -3 rope_new.py <%1\test961.txt >out_py_new.txt
py -3 rope_new.py <%1\test962.txt >out_py_new.txt
py -3 rope_new.py <%1\test963.txt >out_py_new.txt
py -3 rope_new.py <%1\test964.txt >out_py_new.txt
py -3 rope_new.py <%1\test965.txt >out_py_new.txt
py -3 rope_new.py <%1\test966.txt >out_py_new.txt
py -3 rope_new.py <%1\test967.txt >out_py_new.txt
py -3 rope_new.py <%1\test968.txt >out_py_new.txt
py -3 rope_new.py <%1\test969.txt >out_py_new.txt
py -3 rope_new.py <%1\test970.txt >out_py_new.txt
py -3 rope_new.py <%1\test971.txt >out_py_new.txt
py -3 rope_new.py <%1\test972.txt >out_py_new.txt
py -3 rope_new.py <%1\test973.txt >out_py_new.txt
py -3 rope_new.py <%1\test974.txt >out_py_new.txt
py -3 rope_new.py <%1\test975.txt >out_py_new.txt
py -3 rope_new.py <%1\test976.txt >out_py_new.txt
py -3 rope_new.py <%1\test977.txt >out_py_new.txt
py -3 rope_new.py <%1\test978.txt >out_py_new.txt
py -3 rope_new.py <%1\test979.txt >out_py_new.txt
py -3 rope_new.py <%1\test980.txt >out_py_new.txt
py -3 rope_new.py <%1\test981.txt >out_py_new.txt
py -3 rope_new.py <%1\test982.txt >out_py_new.txt
py -3 rope_new.py <%1\test983.txt >out_py_new.txt
py -3 rope_new.py <%1\test984.txt >out_py_new.txt
py -3 rope_new.py <%1\test985.txt >out_py_new.txt
py -3 rope_new.py <%1\test986.txt >out_py_new.txt
py -3 rope_new.py <%1\test987.txt >out_py_new.txt
py -3 rope_new.py <%1\test988.txt >out_py_new.txt
py -3 rope_new.py <%1\test989.txt >out_py_new.txt
py -3 rope_new.py <%1\test990.txt >out_py_new.txt
py -3 rope_new.py <%1\test991.txt >out_py_new.txt
py -3 rope_new.py <%1\test992.txt >out_py_new.txt
py -3 rope_new.py <%1\test993.txt >out_py_new.txt
py -3 rope_new.py <%1\test994.txt >out_py_new.txt
py -3 rope_new.py <%1\test995.txt >out_py_new.txt
py -3 rope_new.py <%1\test996.txt >out_py_new.txt
py -3 rope_new.py <%1\test997.txt >out_py_new.txt
py -3 rope_new.py <%1\test998.txt >out_py_new.txt
py -3 rope_new.py <%1\test999.txt >out_py_new.txt
echo after  %time%